package com.poshanforlife.api.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;

/**
 * Financial ledger entry. Created here by the service-assignment flow
 * (activation for priced items); the /api/transactions endpoints and invoice
 * rendering arrive with the transactions prompt. transactionId and
 * invoiceNumber are generated by {@link
 * com.poshanforlife.api.service.TransactionNumbers}.
 */
@Getter
@Setter
@Entity
@Table(name = "transactions")
public class Transaction extends BaseEntity {

    @Column(name = "transaction_id", nullable = false, unique = true, length = 32)
    private String transactionId;

    @Column(name = "invoice_number", nullable = false, unique = true, length = 20)
    private String invoiceNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 16)
    private TransactionType transactionType;

    @Enumerated(EnumType.STRING)
    @Column(name = "payment_type", nullable = false, length = 16)
    private PaymentType paymentType;

    @Column(name = "price_inr", nullable = false, precision = 10, scale = 2)
    private BigDecimal priceInr;

    @Column(name = "discount_inr", nullable = false, precision = 10, scale = 2)
    private BigDecimal discountInr = BigDecimal.ZERO;

    @Column(name = "amount_inr", nullable = false, precision = 10, scale = 2)
    private BigDecimal amountInr;

    /** Negative when credit is consumed; zero otherwise. */
    @Column(name = "credit_charged", nullable = false, precision = 10, scale = 2)
    private BigDecimal creditCharged = BigDecimal.ZERO;

    @Column(nullable = false, length = 32)
    private String source = "admin";

    @Column(name = "payment_gateway_ref", length = 255)
    private String paymentGatewayRef;

    @Column(columnDefinition = "text")
    private String notes;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "patient_id", nullable = false)
    private User patient;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "created_by", nullable = false)
    private User createdBy;
}
